<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Acc_Etablissement_Penitentiaire</name>
   <tag></tag>
   <elementGuidId>1455125f-886f-4833-a328-358e66f77a37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;sortant_etablissement_penitentiaire&quot;]/app-accordeaon-sortant-etablissement-penitentiaire/section/h3/button|//*[@id=&quot;sortant_etablissement_penitentiaire&quot;]/app-accordeaon-sortant-etablissement-penitentiaire/section/h3/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
