<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Acc_Documents_De_Voyage</name>
   <tag></tag>
   <elementGuidId>ef4cb8e2-9b60-4e9a-9135-39f6b4d3815f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;documents_de_voyage&quot;]/app-accordeon-documents-de-voyage/section/h3/button|//*[@id=&quot;accordeon-documents-de-voyage&quot;]/section/h3/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
