<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_radio_Nature_Acte_AME_Expulsion</name>
   <tag></tag>
   <elementGuidId>7cc0f908-0387-44cc-9d0a-ee7f3a8b43a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ACCORDEON_FONDEMENT_LEGAL&quot;]/form//app-dsfr-radio/div//label[contains(text(),&quot;AME&quot;)]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
