<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_radio_Poursuite_Procedure_Expulsion_Oui</name>
   <tag></tag>
   <elementGuidId>230f92a3-c10e-4240-a638-b272819d3a69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;radio-poursuite-procedure-expulsion-comex&quot;]/div/fieldset//label[contains(text(),'Oui')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
