<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_radio_Poursuite_Procedure_Expulsion_Non</name>
   <tag></tag>
   <elementGuidId>0098da39-28ac-4dd3-85d9-86f3b97cba95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;radio-poursuite-procedure-expulsion-comex&quot;]/div/fieldset//label[contains(text(),'Non')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
