<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_radio_Avis_Comex_Favorable</name>
   <tag></tag>
   <elementGuidId>a0499071-684b-402c-ac85-60a73341cc6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ACCORDEON_COMEX&quot;]/form//app-dsfr-radio[2]/div/fieldset//label[contains(text(),'Favorable')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
