<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Message_Erreur_Duree_ITF_Mois</name>
   <tag></tag>
   <elementGuidId>32c4ed1d-126e-4a83-bc18-3a5e8bd78a0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-accordeon-mesure-judiciaire/section/div/form/div/div[1]/div/fieldset/div[1]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
