<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_radio_Decision_Eloignement_Concernee</name>
   <tag></tag>
   <elementGuidId>34383942-a7d2-4445-b84a-7bfda9d28f97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//app-add-decision-modal//form/app-dsfr-radio/div/fieldset//label)[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
