<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Heure_Notification_Abrogation</name>
   <tag></tag>
   <elementGuidId>c50c9236-83c5-4fa9-9a5f-ab3f3c4b51df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-add-notifcation-abrogation-modal//app-dsfr-input/div/input[@id=&quot;heure_notification&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
