<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date_Notification_Abrogation</name>
   <tag></tag>
   <elementGuidId>f52f2f82-ff3e-4f84-b4b3-a4d18298d39f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-add-notifcation-abrogation-modal//app-dsfr-input/div/input[@name=&quot;date_notification&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
