<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ajouter_Fichier_Notification</name>
   <tag></tag>
   <elementGuidId>b6a1fc57-1b04-4ea0-8557-460d138af0c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-notification-modal//form//app-dsfr-piece-jointe//input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
