<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date_Notification</name>
   <tag></tag>
   <elementGuidId>82a3431f-3f6f-4749-b01a-60568c26a741</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-notification-modal//form//app-dsfr-input/div/input[@name=&quot;date_notification&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
