<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Heure_Notification</name>
   <tag></tag>
   <elementGuidId>2e31350d-4576-4343-a3d1-d905ce42aff2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-notification-modal//form//app-dsfr-input/div/input[@id=&quot;heure_notification&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
