<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_radio_Issue_ANNULE</name>
   <tag></tag>
   <elementGuidId>dbbb4193-e7ea-4e63-89d0-5e8b7ee034ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ACCORDEON_DEPART_PROGRAMME&quot;]/form//div/app-dsfr-radio-arr/div/fieldset//label[contains(text(),&quot;Annulé&quot;)]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
