<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_radio_Protection_Contre_Eloignement_Non</name>
   <tag></tag>
   <elementGuidId>5370e079-636e-43cf-a7b0-d106d88429f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-accordeon-mesures-execution/section/div/app-mesure-placement-retention/form//app-dsfr-radio-arr/div/fieldset//label[contains(text(),&quot;Non&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
