<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_radio_decision_Recours_Contentieux</name>
   <tag></tag>
   <elementGuidId>35231899-31f0-498a-a030-e57501262d57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//app-accordeon-recours-contentieux-administratifs/section//app-dsfr-input-checkbox//label)[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
