<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_radio_Issue_BE</name>
   <tag></tag>
   <elementGuidId>2c60a24f-0d03-46d7-a6a6-989fbb0bbdee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ACCORDEON_DEPART_PROGRAMME&quot;]/form//div/app-dsfr-radio-arr/div/fieldset//label[contains(text(),&quot;BE&quot;)]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
