<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_radio_Escorte_Non</name>
   <tag></tag>
   <elementGuidId>a1a8236d-cc5f-42cb-8813-ce0430f2d900</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-accordeon-depart-programme/section/div/form//app-dsfr-radio-arr/div/fieldset//label[contains(text(),&quot;Non&quot;)]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
