<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_radio_Escorte_Oui</name>
   <tag></tag>
   <elementGuidId>be438ca4-e159-47ce-ad7a-2f0ba66e3dfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-accordeon-depart-programme/section/div/form//app-dsfr-radio-arr/div/fieldset//label[contains(text(),&quot;Oui&quot;)]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
