<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fichier_Visite_Domiciliaire</name>
   <tag></tag>
   <elementGuidId>e415a094-ae0e-4393-a6c1-24d3bae17db0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-visite-domiciliaire//app-dsfr-piece-jointe//input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
