<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Fondement_Legal_Mesure</name>
   <tag></tag>
   <elementGuidId>bb7ced0a-2df0-4893-8f43-4074a7aae14b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-accordeon-mesures-execution/section/div//form//app-dsfr-select-arr/div/select[@name=&quot;fondement_legal&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
