<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Fondement_Legal_Assignation_Residence</name>
   <tag></tag>
   <elementGuidId>8bcd471c-7b35-439b-8aed-ec42ac97e856</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-mesure-assignation-residence/form//app-dsfr-select-arr/div/select[@name=&quot;fondement_legal&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
