<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Fondement_Legal_Reexamen</name>
   <tag></tag>
   <elementGuidId>24cad683-4fa7-46e1-b298-3e677fd4b16e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-accordeon-reexamen-arrete-expulsion/section/div/form//app-dsfr-select-arr/div/select[@name=&quot;fondement_legal&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
