<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Numero_etranger</name>
   <tag></tag>
   <elementGuidId>eefbece8-6a9c-430f-a1c2-2fb392ae0220</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-identite-declaree-search-box//div/app-dsfr-input/div/input[@id=&quot;identifiant_agdref&quot;]|//app-search-box//div/app-dsfr-input/div/input[@id=&quot;identifiant_agdref&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
